import logging
from typing import Optional

from a2ui.basic_catalog.provider import BasicCatalog
from a2ui.parser.parser import has_a2ui_parts, parse_response
from a2ui.schema.manager import A2uiSchemaManager
from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_response import LlmResponse

logger = logging.getLogger(__name__)


def build_a2ui_system_prompt(role_description: str, version: str = "0.8") -> str:
    """Builds system prompt for the agent using A2uiSchemaManager and BasicCatalog.

    Args:
        role_description: Base description of the agent's role and capabilities.
        version: A2UI schema version (default '0.8').

    Returns:
        Combined system instruction string containing role description and A2UI schema rules.
    """
    bc = BasicCatalog()
    manager = A2uiSchemaManager(version=version, catalogs=[bc.get_config(version)])
    a2ui_prompt = manager.generate_system_prompt(role_description=role_description)
    return a2ui_prompt


def a2ui_after_model_callback(
    callback_context: CallbackContext, llm_response: LlmResponse
) -> Optional[LlmResponse]:
    """After model callback that inspects and validates A2UI payloads generated by the model.

    Args:
        callback_context: ADK callback context.
        llm_response: Response generated by the LLM.

    Returns:
        Modified LlmResponse if needed, or None to pass through.
    """
    if not llm_response or not getattr(llm_response, "content", None):
        return None

    try:
        candidates = getattr(llm_response.content, "candidates", []) or []
        for candidate in candidates:
            content = getattr(candidate, "content", None)
            parts = getattr(content, "parts", []) or []
            for part in parts:
                text = getattr(part, "text", "") or ""
                if text and has_a2ui_parts(text):
                    parsed_parts = parse_response(text)
                    logger.info(
                        f"Parsed {len(parsed_parts)} A2UI parts from model response."
                    )
    except Exception as e:
        logger.warning(f"A2UI after_model_callback processing notice: {e}")

    return None
